
skillMetadata:
  sections:
    - name: Mycroft Mouth Settings
      fields:
        - type: label
          label: Settings specific to using a Yamaha reciever with MusicCast and the Mycroft 3.5mm audio jack connected to the AUX port.
        - name: use_yamaha
          type: checkbox
          label: Use Yamaha
          value: "false"
        - name: yamaha_ip
          type: text
          label: Yamaha IP Address
          value: ""
          placeholder: 192.168.1.100
        - name: api_string
          type: text
          label: API String
          value: ""
          placeholder: api string
    - name: Login << Name of another section
      fields:
        - type: label
          label: Just a little bit of extra info for the user to understand following settings
        - name: username
          type: text
          label: Username
          value: ""
        - name: password
          type: password
          label: Password
          value: ""
